name: Call the Repo Workflow to Generate PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  call-generate-pr-description:
    uses: class90431/pr-description-generator/.github/workflows/auto-pr-description.yaml@main
    with:
      repository_owner: ${{ github.repository_owner }}
      repository_name: ${{ github.event.repository.name }}
      pull_request_number: ${{ github.event.pull_request.number }}
      branch_name: ${{ github.event.pull_request.head.ref }}
